#Action name
name: deploy-manifest

# when should this be executed. Whenever there is a push and there are changes in the auth directory
on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

# Things to do whenever a push request is executed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #Checkout code
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment auth-depl
      - run: kubectl apply -f infra/k8s
