# Name of the workflow
name: tests-tickets

# When to run this workflow. Pull requests and for only changes in the tickets directory
on:
  pull_request:
    paths:
      - 'tickets/**'

# Things to do whenever a pull request is create, updated or reopened
#   Start up a virtual machine  (Container) and run Uduntu
#   Take all the code out of the project (Uses step)
#   Then run a series of commands
#     1. Run all tests for Auth service
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
